export enum Feature {
  Bay = 'Bay',
  Beach = 'Beach',
  Canal = 'Canal',
  Forest = 'Forest',
  Island = 'Island',
  Lake = 'Lake',
  Mountain = 'Mountain',
  Plateau = 'Plateau',
  Reserve = 'Reserve',
  River = 'River',
  Sea = 'Sea',
  Valley = 'Valley',
  Plain = 'Plain',
}
